---
# tasks file for cron_scripts

- name: Ensure cron is installed
  apt:
    name: cron
    state: present

- name: Copy script files to server
  template:
    backup: yes
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items: "{{ cron_scripts_list }}"

- name: Update entries to crontab
  cron:
    backup: yes
    name: "{{ item.name | default(item.dest) }}"
    job: "{{ item.dest }}"
    user: "{{ item.owner | default(omit) }}" # The specific user whose crontab should be modified
    state: "{{ item.state | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    cron_file: "{{ item.cron_file | default(omit) }}"
    disabled: "{{ item.disabled | default(omit) }}"
    reboot: "{{ item.reboot | default(omit) }}"
  with_items: "{{ cron_scripts_list }}"
